#
# Makefile for ZOLC initialization sequence generator with Salto
#
#

TARGET = suifvm

CPP = g++
LD  = $(CPP)
CPPFLAGS = -g -Wall
CFLAGS = -Wall -O2
LDFLAGS =
INCLUDEDIR = -I$(SALTO_HOME)/include/salto
LIBDIR = -L$(SALTO_HOME)/lib
RM = rm

all: zolcgen

zolcgen: zolcgen.cc
	$(CPP) $(CPPFLAGS) $(INCLUDEDIR) zolcgen.cc -o zolcgen \
		 $(LIBDIR) -lsalto -lsalto$(TARGET)

clean:
	$(RM) -f zolcgen
